version = 0.1
[default.deploy.parameters]
stack_name = "eb-api-destinations"
resolve_s3 = true
s3_prefix = "eb-api-destinations"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
