# To use this file you need REST Client VS Code extension.

@host = https://maae1hs5sg.execute-api.eu-north-1.amazonaws.com
@stage = dev-pawel

#### Functionless: correct request
POST https://z7vt3qux27.execute-api.eu-north-1.amazonaws.com/message
Content-Type: application/json

{
  "a": 48,
  "b": 84,
  "text": "Serverless is AWSome"
}

#### Functionless: correct request
POST {{host}}/{{stage}}/functionless
Content-Type: application/json

{
  "a": 10,
  "b": 20,
  "text": "Functionless is COOL!"
}

#### Functionless: wrong request
POST {{host}}/{{stage}}/functionless
Content-Type: application/json

{
  "b": 20,
  "text": "Bad request - results in 400"
}


#### Functionless: x-www-form-urlencoded to SQS
POST {{host}}/{{stage}}/urlencoded
Content-Type: application/x-www-form-urlencoded

a=1&b=2&text=Functionless is COOL!
